import { useMemo, useState } from 'react';
import { Badge, Button, Card, Container, Group, Modal, Select, SimpleGrid, Stack, Tabs, Text, TextInput, Textarea, Title } from '@mantine/core';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarRange, Pencil, Plus, Printer, Trash2 } from 'lucide-react';
import { createFacultyPlan, deleteFacultyPlan, fetchClasses, fetchFacultyPlans, fetchSubjects, updateFacultyPlan, type FacultyPlan, type FacultyPlanInput, type PlanPeriod } from '../api/client';
import { printHtml } from '../lib/printDoc';
import { useAuth } from '../stores/auth';

const empty = (period_type: PlanPeriod): FacultyPlanInput => ({ period_type, title: '', start_date: new Date().toISOString().slice(0, 10), end_date: new Date().toISOString().slice(0, 10), status: 'draft', lessons: '', activities: '', schedule: '', objectives: '', resources: '', assessment: '', notes: '' });
const escapeHtml = (value: unknown) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const block = (label: string, value: string | null) => `<section><h2>${escapeHtml(label)}</h2><div>${escapeHtml(value || '—').replace(/\n/g, '<br>')}</div></section>`;

function reportHtml(plans: FacultyPlan[], period: PlanPeriod) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${period} faculty plans</title><style>
  @page{size:A4;margin:14mm}body{font-family:Arial,sans-serif;color:#17202a;font-size:11px}h1{font-size:20px;margin:0 0 4px;color:#123b64}header{border-bottom:3px solid #b28a25;margin-bottom:14px;padding-bottom:8px}.plan{break-after:page}.plan:last-child{break-after:auto}h2{font-size:11px;text-transform:uppercase;color:#123b64;margin:13px 0 4px;border-bottom:1px solid #ccd5df;padding-bottom:2px}section div{white-space:normal;line-height:1.45}.meta{display:grid;grid-template-columns:1fr 1fr;gap:5px 18px;background:#f3f6f9;padding:8px}.sign{display:flex;justify-content:space-between;margin-top:30px;color:#555}</style></head><body>
  ${plans.map((p) => `<article class="plan"><header><h1>${escapeHtml(p.title)}</h1><div>${escapeHtml(p.period_type.toUpperCase())} PLAN · ${escapeHtml(p.start_date)} to ${escapeHtml(p.end_date)}</div></header><div class="meta"><div><b>Faculty:</b> ${escapeHtml(p.faculty_name || '—')}</div><div><b>Status:</b> ${escapeHtml(p.status)}</div><div><b>Class/Section:</b> ${escapeHtml(p.section_name || '—')}</div><div><b>Subject:</b> ${escapeHtml(p.subject_name || '—')}</div></div>${block('Learning objectives', p.objectives)}${block('Lessons / topics', p.lessons)}${block('Activities', p.activities)}${block('Schedule / sequence', p.schedule)}${block('Resources', p.resources)}${block('Assessment / evidence', p.assessment)}${block('Notes / follow-up', p.notes)}<div class="sign"><span>Faculty signature</span><span>Coordinator / Principal</span></div></article>`).join('')}</body></html>`;
}

export function FacultyPlannerScreen() {
  const token = useAuth((s) => s.token)!; const qc = useQueryClient();
  const [period, setPeriod] = useState<PlanPeriod>('daily'); const [editing, setEditing] = useState<FacultyPlan | null>(null);
  const [form, setForm] = useState<FacultyPlanInput>(empty('daily')); const [opened, setOpened] = useState(false);
  const plansQuery = useQuery({ queryKey: ['faculty-plans', period], queryFn: () => fetchFacultyPlans(token, period) });
  const subjectsQuery = useQuery({ queryKey: ['subjects'], queryFn: () => fetchSubjects(token) });
  const classesQuery = useQuery({ queryKey: ['classes'], queryFn: () => fetchClasses(token) });
  const invalidate = () => qc.invalidateQueries({ queryKey: ['faculty-plans'] });
  const save = useMutation({ mutationFn: () => editing ? updateFacultyPlan(token, editing.id, form) : createFacultyPlan(token, form), onSuccess: () => { setOpened(false); setEditing(null); invalidate(); } });
  const remove = useMutation({ mutationFn: (id: number) => deleteFacultyPlan(token, id), onSuccess: invalidate });
  const plans = plansQuery.data?.plans ?? [];
  const sections = useMemo(() => (classesQuery.data?.classes ?? []).flatMap((c) => c.sections.map((s) => ({ value: String(s.id), label: `${c.name ?? 'Class'} – ${s.name ?? 'Section'}` }))), [classesQuery.data]);
  const subjects = (subjectsQuery.data?.subjects ?? []).map((s) => ({ value: String(s.id), label: s.name ?? `Subject ${s.id}` }));
  const set = <K extends keyof FacultyPlanInput>(key: K, value: FacultyPlanInput[K]) => setForm((old) => ({ ...old, [key]: value }));
  const startNew = () => { setEditing(null); setForm(empty(period)); setOpened(true); };
  const startEdit = (p: FacultyPlan) => { setEditing(p); setForm({ ...p }); setOpened(true); };
  const switchPeriod = (value: string | null) => { const next = (value ?? 'daily') as PlanPeriod; setPeriod(next); };

  return <Container size="xl" py="md"><Stack gap="md">
    <Group justify="space-between"><div><Title order={2}>Faculty Planner</Title><Text size="sm" c="dimmed">Manually maintain lesson, activity, and scheduling plans for print or PDF.</Text></div><Group><Button data-testid="faculty-planner-print-report-button" variant="default" leftSection={<Printer size={15}/>} disabled={!plans.length} onClick={() => printHtml(reportHtml(plans, period))}>Print {period} report</Button><Button data-testid="faculty-planner-new-button" leftSection={<Plus size={15}/>} onClick={startNew}>New plan</Button></Group></Group>
    <Tabs value={period} onChange={switchPeriod}><Tabs.List><Tabs.Tab data-testid="faculty-planner-daily-tab" value="daily">Daily</Tabs.Tab><Tabs.Tab data-testid="faculty-planner-weekly-tab" value="weekly">Weekly</Tabs.Tab><Tabs.Tab data-testid="faculty-planner-monthly-tab" value="monthly">Monthly</Tabs.Tab></Tabs.List></Tabs>
    {!plans.length ? <Card withBorder py="xl"><Text ta="center" c="dimmed">No {period} plans yet. Faculty can enter one manually using New plan.</Text></Card> : <SimpleGrid cols={{ base: 1, md: 2 }}>{plans.map((p) => <Card key={p.id} withBorder><Stack gap="xs"><Group justify="space-between"><Text fw={700}>{p.title}</Text><Badge color={p.status === 'completed' ? 'teal' : p.status === 'ready' ? 'blue' : 'gray'}>{p.status}</Badge></Group><Text size="xs" c="dimmed">{p.start_date}{p.end_date !== p.start_date ? ` – ${p.end_date}` : ''} · {p.section_name || 'All classes'} · {p.subject_name || 'General'}</Text><Text size="sm" lineClamp={3}>{p.lessons || p.activities || p.schedule || 'No plan details entered.'}</Text><Group justify="flex-end"><Button size="compact-xs" variant="subtle" leftSection={<Printer size={12}/>} onClick={() => printHtml(reportHtml([p], p.period_type))}>Print</Button><Button size="compact-xs" variant="subtle" leftSection={<Pencil size={12}/>} onClick={() => startEdit(p)}>Edit</Button><Button size="compact-xs" variant="subtle" color="red" leftSection={<Trash2 size={12}/>} onClick={() => remove.mutate(p.id)}>Delete</Button></Group></Stack></Card>)}</SimpleGrid>}
  </Stack>
  <Modal opened={opened} onClose={() => setOpened(false)} title={editing ? 'Edit faculty plan' : `New ${period} plan`} size="xl"><Stack>
    <SimpleGrid cols={{ base: 1, sm: 2 }}><TextInput data-testid="faculty-plan-title-input" label="Plan title" required value={form.title} onChange={(e) => set('title', e.currentTarget.value)}/><Select label="Status" data={[{value:'draft',label:'Draft'},{value:'ready',label:'Ready'},{value:'completed',label:'Completed'}]} value={form.status} onChange={(v) => set('status', (v ?? 'draft') as FacultyPlan['status'])}/><TextInput data-testid="faculty-plan-start-date-input" label="Start date" type="date" required value={form.start_date} onChange={(e) => set('start_date', e.currentTarget.value)}/><TextInput data-testid="faculty-plan-end-date-input" label="End date" type="date" required value={form.end_date} onChange={(e) => set('end_date', e.currentTarget.value)}/><Select label="Class / section" clearable searchable data={sections} value={form.section_id ? String(form.section_id) : null} onChange={(v) => set('section_id', v ? Number(v) : null)}/><Select label="Subject" clearable searchable data={subjects} value={form.subject_id ? String(form.subject_id) : null} onChange={(v) => set('subject_id', v ? Number(v) : null)}/></SimpleGrid>
    <Textarea label="Learning objectives" autosize minRows={2} value={form.objectives ?? ''} onChange={(e) => set('objectives', e.currentTarget.value)}/><Textarea label="Lessons / topics" autosize minRows={3} value={form.lessons ?? ''} onChange={(e) => set('lessons', e.currentTarget.value)}/><Textarea label="Activities" autosize minRows={3} value={form.activities ?? ''} onChange={(e) => set('activities', e.currentTarget.value)}/><Textarea label="Schedule / sequence" description="Enter periods, time blocks, or the intended order manually." autosize minRows={3} value={form.schedule ?? ''} onChange={(e) => set('schedule', e.currentTarget.value)}/><SimpleGrid cols={{base:1,sm:2}}><Textarea label="Resources" autosize minRows={2} value={form.resources ?? ''} onChange={(e) => set('resources', e.currentTarget.value)}/><Textarea label="Assessment / evidence" autosize minRows={2} value={form.assessment ?? ''} onChange={(e) => set('assessment', e.currentTarget.value)}/></SimpleGrid><Textarea label="Notes / follow-up" autosize minRows={2} value={form.notes ?? ''} onChange={(e) => set('notes', e.currentTarget.value)}/>
    <Group justify="flex-end"><Button variant="default" onClick={() => setOpened(false)}>Cancel</Button><Button data-testid="faculty-plan-save-button" leftSection={<CalendarRange size={15}/>} loading={save.isPending} disabled={!form.title.trim() || !form.start_date || !form.end_date || form.end_date < form.start_date} onClick={() => save.mutate()}>Save plan</Button></Group>
  </Stack></Modal></Container>;
}
