import { useEffect, useState } from 'react';
import { Alert, Badge, Button, Card, Code, CopyButton, Group, NumberInput, Stack, Text, TextInput, Title } from '@mantine/core';
import { Copy, Link, Radio, Unplug, Wifi } from 'lucide-react';

type Status={mode:'off'|'host'|'client';running:boolean;port:number;addresses:string[];pairingCode:string|null;remoteUrl:string|null;connected:boolean;lastError:string|null};
export function LanConnectionManager({onConnected,compact=false}:{onConnected?:()=>void;compact?:boolean}){
  const [status,setStatus]=useState<Status|null>(null);const [url,setUrl]=useState('');const [code,setCode]=useState('');const [port,setPort]=useState(8788);const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const bridge=window.leosDesktop;const refresh=async()=>{if(bridge)setStatus(await bridge.lanStatus());};useEffect(()=>{void refresh();},[]);
  const run=async(name:string,fn:()=>Promise<Status>)=>{setBusy(name);setError('');try{const next=await fn();setStatus(next);if(next.mode==='client')onConnected?.();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('');}};
  if(!bridge)return <Alert color="yellow">LAN connections are available in the LEOS desktop application.</Alert>;
  return <Stack><Group justify="space-between"><div><Title order={compact?4:2}>LAN Connection Manager</Title><Text size="sm" c="dimmed">Share one open school securely across computers on the same private network.</Text></div><Badge size="lg" color={status?.mode==='host'?'green':status?.mode==='client'?'blue':'gray'}>{status?.mode==='host'?'Hosting':status?.mode==='client'?'Connected':'Offline'}</Badge></Group>{error&&<Alert color="red" withCloseButton onClose={()=>setError('')}>{error}</Alert>}
  {status?.mode==='host'?<Card withBorder><Stack><Text fw={700}>This computer is the host</Text><Text size="sm">Keep LEOS open. On another computer or phone, open one of these addresses in a browser, enter the temporary pairing code, then sign in.</Text>{status.addresses.map(a=><Group key={a}><Code>{a}</Code><CopyButton value={a}>{({copy,copied})=><Button size="compact-xs" variant="light" onClick={copy} leftSection={<Copy size={12}/>}>{copied?'Copied':'Copy'}</Button>}</CopyButton></Group>)}<Group><Text>Pairing code:</Text><Code fw={800} fz="lg">{status.pairingCode}</Code><CopyButton value={status.pairingCode??''}>{({copy,copied})=><Button size="compact-xs" variant="light" onClick={copy}>{copied?'Copied':'Copy'}</Button>}</CopyButton></Group><Alert color="yellow">Use only on a trusted school network. The pairing code protects access but HTTP traffic is not encrypted.</Alert><Button color="red" variant="light" leftSection={<Unplug size={15}/>} loading={busy==='stop'} onClick={()=>run('stop',()=>bridge.lanStop())}>Stop hosting</Button></Stack></Card>:status?.mode==='client'?<Card withBorder><Stack><Text fw={700}>Connected to {status.remoteUrl}</Text><Text size="sm" c="dimmed">Sign in with an account stored on the host school computer.</Text><Button variant="light" color="red" leftSection={<Unplug size={15}/>} onClick={()=>run('disconnect',()=>bridge.lanDisconnect())}>Disconnect</Button></Stack></Card>:<Group align="stretch" grow wrap="wrap">{!compact&&<Card withBorder miw={280}><Stack><Group><Radio size={18}/><Text fw={700}>Host this school</Text></Group><Text size="sm" c="dimmed">Makes the open school available to paired LEOS desktop clients and ordinary web browsers on this LAN.</Text><NumberInput label="Network port" min={1024} max={65535} value={port} onChange={v=>setPort(Number(v)||8788)}/><Button leftSection={<Wifi size={15}/>} loading={busy==='host'} onClick={()=>run('host',()=>bridge.lanStart(port))}>Start hosting</Button></Stack></Card>}<Card withBorder miw={280}><Stack><Group><Link size={18}/><Text fw={700}>Connect to a host</Text></Group><TextInput label="Host address" placeholder="http://192.168.1.20:8788" value={url} onChange={e=>setUrl(e.currentTarget.value)}/><TextInput label="Pairing code" placeholder="Ask the host" value={code} onChange={e=>setCode(e.currentTarget.value.toUpperCase())}/><Button disabled={!url||code.length<6} loading={busy==='connect'} onClick={()=>run('connect',()=>bridge.lanConnect(url,code))}>Connect</Button></Stack></Card></Group>}</Stack>;
}
