import { useEffect, useState } from 'react';
import { Alert, Badge, Button, Card, Checkbox, Container, Divider, Grid, Group, NumberInput, Select, Stack, Tabs, Text, TextInput, Textarea, Title } from '@mantine/core';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookOpen, ClipboardCheck, Plus } from 'lucide-react';
import { createLmsAssignment, createLmsLesson, createLmsModule, createLmsSpace, fetchClasses, fetchLmsSpace, fetchLmsSpaces, fetchLmsSubmissions, fetchPortalProfile, fetchSubjects, gradeLmsSubmission, submitLmsAssignment, type LmsAssignment } from '../api/client';
import { useAuth } from '../stores/auth';

export function LmsScreen(){
  const token=useAuth((s)=>s.token)!; const user=useAuth((s)=>s.user)!; const qc=useQueryClient();
  const learner=user.profile==='student'||user.profile==='parent'; const student=user.profile==='student';
  const [selected,setSelected]=useState<number|null>(null); const [notice,setNotice]=useState('');
  const spaces=useQuery({queryKey:['lms-spaces'],queryFn:()=>fetchLmsSpaces(token)});
  useEffect(()=>{if(selected==null&&spaces.data?.spaces[0])setSelected(spaces.data.spaces[0].id);},[selected,spaces.data]);
  const detail=useQuery({queryKey:['lms-space',selected],queryFn:()=>fetchLmsSpace(token,selected!),enabled:selected!=null});
  const classes=useQuery({queryKey:['classes'],queryFn:()=>fetchClasses(token),enabled:!learner});
  const subjects=useQuery({queryKey:['subjects'],queryFn:()=>fetchSubjects(token),enabled:!learner});
  const profile=useQuery({queryKey:['portal-profile'],queryFn:()=>fetchPortalProfile(token),enabled:learner});
  const refresh=async()=>{await qc.invalidateQueries({queryKey:['lms-spaces']});await qc.invalidateQueries({queryKey:['lms-space',selected]});};
  const [spaceForm,setSpaceForm]=useState({title:'',description:'',section_id:'',subject_id:'',published:false});
  const [moduleForm,setModuleForm]=useState({title:'',description:'',published:false});
  const [lessonForm,setLessonForm]=useState({module_id:'',title:'',content:'',objectives:'',resources:'',published:false});
  const [assignmentForm,setAssignmentForm]=useState({module_id:'',title:'',instructions:'',due_date:'',max_points:100,published:false});
  const [submissionText,setSubmissionText]=useState<Record<number,string>>({});
  const createSpace=useMutation({mutationFn:()=>createLmsSpace(token,{title:spaceForm.title,description:spaceForm.description||null,section_id:Number(spaceForm.section_id),subject_id:spaceForm.subject_id?Number(spaceForm.subject_id):null,is_published:spaceForm.published}),onSuccess:async(r)=>{setSpaceForm({title:'',description:'',section_id:'',subject_id:'',published:false});await refresh();setSelected(r.id);}});
  const addModule=useMutation({mutationFn:()=>createLmsModule(token,{space_id:selected!,title:moduleForm.title,description:moduleForm.description||null,is_published:moduleForm.published}),onSuccess:()=>{setModuleForm({title:'',description:'',published:false});refresh();}});
  const addLesson=useMutation({mutationFn:()=>createLmsLesson(token,{module_id:Number(lessonForm.module_id),title:lessonForm.title,content:lessonForm.content||null,objectives:lessonForm.objectives||null,resources:lessonForm.resources||null,is_published:lessonForm.published}),onSuccess:()=>{setLessonForm({module_id:'',title:'',content:'',objectives:'',resources:'',published:false});refresh();}});
  const addAssignment=useMutation({mutationFn:()=>createLmsAssignment(token,{space_id:selected!,module_id:assignmentForm.module_id?Number(assignmentForm.module_id):null,title:assignmentForm.title,instructions:assignmentForm.instructions||null,due_date:assignmentForm.due_date||null,max_points:assignmentForm.max_points,is_published:assignmentForm.published}),onSuccess:()=>{setAssignmentForm({module_id:'',title:'',instructions:'',due_date:'',max_points:100,published:false});refresh();}});
  const submit=useMutation({mutationFn:(a:LmsAssignment)=>submitLmsAssignment(token,{assignment_id:a.id,student_id:profile.data!.students[0].id,content:submissionText[a.id]||null}),onSuccess:()=>{setNotice('Assignment submitted.');refresh();}});
  const classOptions=(classes.data?.classes??[]).flatMap(c=>c.sections.map(s=>({value:String(s.id),label:`${c.name??'Class'} — ${s.name??'Section'}`})));
  const subjectOptions=(subjects.data?.subjects??[]).map(s=>({value:String(s.id),label:s.name??s.code??`Subject ${s.id}`}));
  const moduleOptions=(detail.data?.space.modules??[]).map(m=>({value:String(m.id),label:m.title}));
  const error=spaces.error||detail.error||createSpace.error||addModule.error||addLesson.error||addAssignment.error||submit.error;
  return <Container size="xl" py="md"><Stack><div><Title order={2}>Learning Management</Title><Text size="sm" c="dimmed">Lessons, resources, assignments, submissions, and feedback—stored inside this school file.</Text></div>{notice&&<Alert color="green" withCloseButton onClose={()=>setNotice('')}>{notice}</Alert>}{error&&<Alert color="red">{error.message}</Alert>}
  <Grid><Grid.Col span={{base:12,md:3}}><Stack>{!learner&&<Card withBorder><Stack gap="xs"><Text fw={700}>New learning space</Text><TextInput placeholder="Space title" value={spaceForm.title} onChange={e=>setSpaceForm(f=>({...f,title:e.currentTarget.value}))}/><Select searchable placeholder="Class and section" data={classOptions} value={spaceForm.section_id} onChange={v=>setSpaceForm(f=>({...f,section_id:v??''}))}/><Select searchable clearable placeholder="Subject" data={subjectOptions} value={spaceForm.subject_id} onChange={v=>setSpaceForm(f=>({...f,subject_id:v??''}))}/><Textarea placeholder="Description" value={spaceForm.description} onChange={e=>setSpaceForm(f=>({...f,description:e.currentTarget.value}))}/><Checkbox label="Publish to learners" checked={spaceForm.published} onChange={e=>setSpaceForm(f=>({...f,published:e.currentTarget.checked}))}/><Button leftSection={<Plus size={14}/>} disabled={!spaceForm.title||!spaceForm.section_id} loading={createSpace.isPending} onClick={()=>createSpace.mutate()}>Create</Button></Stack></Card>}{(spaces.data?.spaces??[]).map(s=><Card withBorder key={s.id} onClick={()=>setSelected(s.id)} style={{cursor:'pointer',borderColor:selected===s.id?'var(--mantine-color-blue-6)':undefined}}><Text fw={700}>{s.title}</Text><Text size="xs" c="dimmed">{s.class_name} {s.section_name} · {s.subject_name??'General'}</Text><Group mt="xs" gap="xs"><Badge color={s.is_published?'green':'gray'}>{s.is_published?'Published':'Draft'}</Badge><Badge variant="light">{s.assignments_count??0} tasks</Badge></Group></Card>)}</Stack></Grid.Col>
  <Grid.Col span={{base:12,md:9}}>{detail.data?<Stack><Card withBorder><Group justify="space-between"><div><Title order={3}>{detail.data.space.title}</Title><Text c="dimmed">{detail.data.space.class_name} {detail.data.space.section_name} · {detail.data.space.subject_name??'General learning'}</Text></div><Badge color={detail.data.space.is_published?'green':'gray'}>{detail.data.space.is_published?'Published':'Draft'}</Badge></Group>{detail.data.space.description&&<Text mt="sm">{detail.data.space.description}</Text>}</Card>
  <Tabs defaultValue="lessons"><Tabs.List><Tabs.Tab value="lessons" leftSection={<BookOpen size={14}/>}>Lessons</Tabs.Tab><Tabs.Tab value="assignments" leftSection={<ClipboardCheck size={14}/>}>Assignments</Tabs.Tab>{!learner&&<Tabs.Tab value="author">Add content</Tabs.Tab>}</Tabs.List>
  <Tabs.Panel value="lessons" pt="md"><Stack>{(detail.data.space.modules??[]).map(m=><Card withBorder key={m.id}><Group justify="space-between"><Title order={4}>{m.title}</Title><Badge color={m.is_published?'green':'gray'}>{m.is_published?'Published':'Draft'}</Badge></Group>{m.description&&<Text c="dimmed" size="sm">{m.description}</Text>}<Divider my="sm"/>{m.lessons.map(l=><Card key={l.id} bg="var(--mantine-color-gray-0)" mb="xs"><Group justify="space-between"><Text fw={700}>{l.title}</Text><Badge variant="light">{l.is_published?'Published':'Draft'}</Badge></Group>{l.objectives&&<Text size="sm"><b>Objectives:</b> {l.objectives}</Text>}{l.content&&<Text size="sm" mt="xs" style={{whiteSpace:'pre-wrap'}}>{l.content}</Text>}{l.resources&&<Text size="sm" mt="xs"><b>Resources:</b> {l.resources}</Text>}</Card>)}</Card>)}{!(detail.data.space.modules??[]).length&&<Text c="dimmed">No lessons have been added yet.</Text>}</Stack></Tabs.Panel>
  <Tabs.Panel value="assignments" pt="md"><Stack>{(detail.data.space.assignments??[]).map(a=><AssignmentCard key={a.id} assignment={a} learner={learner} student={student} token={token} text={submissionText[a.id]??''} setText={v=>setSubmissionText(x=>({...x,[a.id]:v}))} onSubmit={()=>submit.mutate(a)} onRefresh={refresh}/>)}</Stack></Tabs.Panel>
  {!learner&&<Tabs.Panel value="author" pt="md"><Grid><Grid.Col span={{base:12,lg:4}}><Card withBorder><Stack><Text fw={700}>Add module</Text><TextInput label="Title" value={moduleForm.title} onChange={e=>setModuleForm(f=>({...f,title:e.currentTarget.value}))}/><Textarea label="Description" value={moduleForm.description} onChange={e=>setModuleForm(f=>({...f,description:e.currentTarget.value}))}/><Checkbox label="Publish" checked={moduleForm.published} onChange={e=>setModuleForm(f=>({...f,published:e.currentTarget.checked}))}/><Button disabled={!moduleForm.title} onClick={()=>addModule.mutate()}>Add module</Button></Stack></Card></Grid.Col><Grid.Col span={{base:12,lg:4}}><Card withBorder><Stack><Text fw={700}>Add lesson</Text><Select label="Module" data={moduleOptions} value={lessonForm.module_id} onChange={v=>setLessonForm(f=>({...f,module_id:v??''}))}/><TextInput label="Title" value={lessonForm.title} onChange={e=>setLessonForm(f=>({...f,title:e.currentTarget.value}))}/><Textarea label="Objectives" value={lessonForm.objectives} onChange={e=>setLessonForm(f=>({...f,objectives:e.currentTarget.value}))}/><Textarea label="Lesson content" value={lessonForm.content} onChange={e=>setLessonForm(f=>({...f,content:e.currentTarget.value}))}/><Textarea label="Resources" value={lessonForm.resources} onChange={e=>setLessonForm(f=>({...f,resources:e.currentTarget.value}))}/><Checkbox label="Publish" checked={lessonForm.published} onChange={e=>setLessonForm(f=>({...f,published:e.currentTarget.checked}))}/><Button disabled={!lessonForm.title||!lessonForm.module_id} onClick={()=>addLesson.mutate()}>Add lesson</Button></Stack></Card></Grid.Col><Grid.Col span={{base:12,lg:4}}><Card withBorder><Stack><Text fw={700}>Add assignment</Text><Select label="Module (optional)" clearable data={moduleOptions} value={assignmentForm.module_id} onChange={v=>setAssignmentForm(f=>({...f,module_id:v??''}))}/><TextInput label="Title" value={assignmentForm.title} onChange={e=>setAssignmentForm(f=>({...f,title:e.currentTarget.value}))}/><Textarea label="Instructions" value={assignmentForm.instructions} onChange={e=>setAssignmentForm(f=>({...f,instructions:e.currentTarget.value}))}/><TextInput type="date" label="Due date" value={assignmentForm.due_date} onChange={e=>setAssignmentForm(f=>({...f,due_date:e.currentTarget.value}))}/><NumberInput label="Maximum points" min={1} value={assignmentForm.max_points} onChange={v=>setAssignmentForm(f=>({...f,max_points:Number(v)||100}))}/><Checkbox label="Publish" checked={assignmentForm.published} onChange={e=>setAssignmentForm(f=>({...f,published:e.currentTarget.checked}))}/><Button disabled={!assignmentForm.title} onClick={()=>addAssignment.mutate()}>Add assignment</Button></Stack></Card></Grid.Col></Grid></Tabs.Panel>}</Tabs></Stack>:<Text c="dimmed">Select a learning space.</Text>}</Grid.Col></Grid></Stack></Container>;
}

function AssignmentCard({assignment:a,learner,student,token,text,setText,onSubmit,onRefresh}:{assignment:LmsAssignment;learner:boolean;student:boolean;token:string;text:string;setText:(v:string)=>void;onSubmit:()=>void;onRefresh:()=>void}){
  const submissions=useQuery({queryKey:['lms-submissions',a.id],queryFn:()=>fetchLmsSubmissions(token,a.id),enabled:!learner});
  const [grades,setGrades]=useState<Record<number,{score:number;feedback:string}>>({}); const grade=useMutation({mutationFn:(id:number)=>gradeLmsSubmission(token,id,grades[id]??{score:0,feedback:''}),onSuccess:()=>{submissions.refetch();onRefresh();}});
  return <Card withBorder><Group justify="space-between"><div><Text fw={700}>{a.title}</Text><Text size="sm" c="dimmed">Due {a.due_date||'not set'} · {a.max_points} points</Text></div><Badge color={a.is_published?'green':'gray'}>{a.is_published?'Published':'Draft'}</Badge></Group>{a.instructions&&<Text mt="sm" style={{whiteSpace:'pre-wrap'}}>{a.instructions}</Text>}{learner&&<Stack mt="sm">{(a.my_submissions??[]).map(s=><Alert key={s.id} color={s.status==='graded'?'green':'blue'}>{s.status}{s.score!=null?` · ${s.score}/${a.max_points}`:''}{s.feedback?` · ${s.feedback}`:''}</Alert>)}{student&&<><Textarea label="Your response" value={text} onChange={e=>setText(e.currentTarget.value)}/><Button onClick={onSubmit} disabled={!text.trim()}>Submit assignment</Button></>}</Stack>}{!learner&&<Stack mt="md"><Text fw={600} size="sm">Student submissions</Text>{(submissions.data?.submissions??[]).map(s=><Card key={s.id} bg="var(--mantine-color-gray-0)"><Text fw={600}>{s.first_name} {s.last_name}</Text><Text size="sm" style={{whiteSpace:'pre-wrap'}}>{s.content||'No written response'}</Text><Group mt="xs" grow><NumberInput min={0} max={a.max_points} placeholder={`Score / ${a.max_points}`} value={grades[s.id]?.score??s.score??0} onChange={v=>setGrades(g=>({...g,[s.id]:{score:Number(v)||0,feedback:g[s.id]?.feedback??s.feedback??''}}))}/><TextInput placeholder="Feedback" value={grades[s.id]?.feedback??s.feedback??''} onChange={e=>setGrades(g=>({...g,[s.id]:{score:g[s.id]?.score??s.score??0,feedback:e.currentTarget.value}}))}/><Button onClick={()=>grade.mutate(s.id)}>Save grade</Button></Group></Card>)}{submissions.data&&!submissions.data.total&&<Text size="sm" c="dimmed">No submissions yet.</Text>}</Stack>}</Card>;
}
