import { useState } from 'react';
import { Alert, Badge, Button, Card, Container, Group, Modal, MultiSelect, PasswordInput, Select, SimpleGrid, Stack, Text, TextInput, Title } from '@mantine/core';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { KeyRound, Plus, Trash2 } from 'lucide-react';
import { createPortalAccount, deletePortalAccount, fetchPortalAccounts, fetchStaff, fetchStudents, resetPortalPassword, type PortalAccount } from '../api/client';
import { useAuth } from '../stores/auth';

type PortalRole='teacher'|'parent'|'student';
export function PortalAccountsScreen(){
  const token=useAuth((s)=>s.token)!;const qc=useQueryClient();const [opened,setOpened]=useState(false);const [reset,setReset]=useState<PortalAccount|null>(null);const [resetPassword,setResetPassword]=useState('');
  const [form,setForm]=useState({username:'',password:'',role:'teacher' as PortalRole,name:'',staff_id:'',student_ids:[] as string[]});
  const accounts=useQuery({queryKey:['portal-accounts'],queryFn:()=>fetchPortalAccounts(token)});const staff=useQuery({queryKey:['staff'],queryFn:()=>fetchStaff(token,{limit:500})});const students=useQuery({queryKey:['students'],queryFn:()=>fetchStudents(token,{limit:500})});
  const invalidate=()=>qc.invalidateQueries({queryKey:['portal-accounts']});
  const create=useMutation({mutationFn:()=>createPortalAccount(token,{username:form.username,password:form.password,role:form.role,name:form.name,staff_id:form.role==='teacher'?Number(form.staff_id):null,student_ids:form.role==='teacher'?[]:form.student_ids.map(Number)}),onSuccess:()=>{setOpened(false);setForm({username:'',password:'',role:'teacher',name:'',staff_id:'',student_ids:[]});invalidate();}});
  const remove=useMutation({mutationFn:(id:number)=>deletePortalAccount(token,id),onSuccess:invalidate});
  const resetMut=useMutation({mutationFn:()=>resetPortalPassword(token,reset!.id,resetPassword),onSuccess:()=>{setReset(null);setResetPassword('');}});
  const staffOptions=(staff.data?.staff??[]).map((s)=>({value:String(s.id),label:`${s.first_name??''} ${s.last_name??''}`.trim()}));const studentOptions=(students.data?.students??[]).map((s)=>({value:String(s.id),label:`${s.first_name} ${s.last_name}`.trim()}));
  const valid=form.username.length>=3&&form.password.length>=8&&form.name.trim()&&(form.role==='teacher'?!!form.staff_id:form.role==='student'?form.student_ids.length===1:form.student_ids.length>0);
  return <Container size="xl" py="md"><Stack><Group justify="space-between"><div><Title order={2}>Portal Accounts</Title><Text size="sm" c="dimmed">Create secure teacher, parent, and student sign-ins linked to existing records.</Text></div><Button leftSection={<Plus size={15}/>} onClick={()=>setOpened(true)} data-testid="portal-account-new-button">New account</Button></Group>
  {accounts.error&&<Alert color="red">{accounts.error.message}</Alert>}<SimpleGrid cols={{base:1,md:2}}>{(accounts.data?.accounts??[]).map((a)=><Card withBorder key={a.id}><Stack gap="xs"><Group justify="space-between"><div><Text fw={700}>{a.name}</Text><Text size="xs" c="dimmed">@{a.username}</Text></div><Badge>{a.role}</Badge></Group><Text size="sm">{a.staff_name||a.student_names||'No linked profile'}</Text><Group justify="flex-end"><Button size="compact-xs" variant="subtle" leftSection={<KeyRound size={12}/>} onClick={()=>setReset(a)}>Reset password</Button><Button size="compact-xs" variant="subtle" color="red" leftSection={<Trash2 size={12}/>} onClick={()=>remove.mutate(a.id)}>Remove</Button></Group></Stack></Card>)}</SimpleGrid>
  <Modal opened={opened} onClose={()=>setOpened(false)} title="Create portal account"><Stack><Select label="Account type" data={[{value:'teacher',label:'Teacher'},{value:'parent',label:'Parent / guardian'},{value:'student',label:'Student'}]} value={form.role} onChange={(v)=>setForm((f)=>({...f,role:(v??'teacher') as PortalRole,staff_id:'',student_ids:[]}))}/><TextInput label="Display name" required value={form.name} onChange={(e)=>setForm((f)=>({...f,name:e.currentTarget.value}))}/><TextInput label="Username" required value={form.username} onChange={(e)=>setForm((f)=>({...f,username:e.currentTarget.value}))}/><PasswordInput label="Temporary password" description="At least 8 characters" required value={form.password} onChange={(e)=>setForm((f)=>({...f,password:e.currentTarget.value}))}/>{form.role==='teacher'?<Select label="Staff profile" searchable required data={staffOptions} value={form.staff_id} onChange={(v)=>setForm((f)=>({...f,staff_id:v??''}))}/>:<MultiSelect label={form.role==='student'?'Student profile':'Children'} searchable required maxValues={form.role==='student'?1:12} data={studentOptions} value={form.student_ids} onChange={(v)=>setForm((f)=>({...f,student_ids:v}))}/>}<Button disabled={!valid} loading={create.isPending} onClick={()=>create.mutate()} data-testid="portal-account-save-button">Create account</Button></Stack></Modal>
  <Modal opened={!!reset} onClose={()=>setReset(null)} title={`Reset password${reset?` — ${reset.name}`:''}`}><Stack><PasswordInput label="New temporary password" description="At least 8 characters" value={resetPassword} onChange={(e)=>setResetPassword(e.currentTarget.value)}/><Button disabled={resetPassword.length<8} loading={resetMut.isPending} onClick={()=>resetMut.mutate()}>Reset password</Button></Stack></Modal>
  </Stack></Container>;
}
