import { Badge, Card, Container, Group, SimpleGrid, Skeleton, Stack, Table, Text, Title } from '@mantine/core';
import { useQuery } from '@tanstack/react-query';
import { BookOpen, CalendarCheck, GraduationCap, UserRound } from 'lucide-react';
import { fetchPortalProfile } from '../api/client';
import { useAuth } from '../stores/auth';

export function PortalProfileScreen(){
  const token=useAuth((s)=>s.token)!;const {data,isLoading,error}=useQuery({queryKey:['portal-profile'],queryFn:()=>fetchPortalProfile(token)});
  if(isLoading)return <Container py="xl"><Skeleton height={220}/></Container>;if(error||!data)return <Container py="xl"><Text c="red">Unable to load the linked profile.</Text></Container>;
  return <Container size="lg" py="md"><Stack><Group><UserRound/><div><Title order={2}>{data.user.name}</Title><Text size="sm" c="dimmed">{data.user.role} portal · @{data.user.username}</Text></div></Group>
  {data.staff&&<Card withBorder><Stack><Group justify="space-between"><Title order={4}>Teacher profile</Title><Badge>Staff</Badge></Group><SimpleGrid cols={{base:1,sm:2,md:3}}><Text><b>Name:</b> {data.staff.first_name} {data.staff.last_name}</Text><Text><b>Employee ID:</b> {data.staff.employee_id||'—'}</Text><Text><b>Department:</b> {data.staff.department||'—'}</Text><Text><b>Email:</b> {data.staff.email||'—'}</Text><Text><b>Phone:</b> {data.staff.phone||'—'}</Text><Text><b>Joined:</b> {data.staff.join_date||'—'}</Text></SimpleGrid><Group><Badge variant="light">{data.staff.sections_count} sections</Badge><Badge variant="light">{data.staff.subjects_count} subjects</Badge></Group></Stack></Card>}
  {data.students.map((student)=><Card withBorder key={student.id}><Stack><Group justify="space-between"><Group><GraduationCap size={18}/><div><Title order={4}>{student.first_name} {student.last_name}</Title><Text size="xs" c="dimmed">{student.class_name||'Class not assigned'}{student.section_name?` – ${student.section_name}`:''}</Text></div></Group><Badge color={student.enrolled?'teal':'gray'}>{student.enrolled?'Enrolled':'Not enrolled'}</Badge></Group><SimpleGrid cols={{base:1,sm:3}}><Card withBorder p="sm"><Group gap="xs"><CalendarCheck size={15}/><Text size="sm">Attendance</Text></Group><Text fw={700} size="xl">{student.attendance_pct===null?'—':`${student.attendance_pct}%`}</Text></Card><Card withBorder p="sm"><Group gap="xs"><BookOpen size={15}/><Text size="sm">Recent results</Text></Group><Text fw={700} size="xl">{student.recent_marks.length}</Text></Card><Card withBorder p="sm"><Text size="sm">Guardian</Text><Text fw={600}>{student.guardian_name||'—'}</Text></Card></SimpleGrid>{student.recent_marks.length>0&&<><Text fw={600}>Recent marks</Text><Table withTableBorder striped><Table.Thead><Table.Tr><Table.Th>Term</Table.Th><Table.Th>Subject</Table.Th><Table.Th>Marks</Table.Th><Table.Th>Grade</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{student.recent_marks.map((m,i)=><Table.Tr key={i}><Table.Td>{m.term||'—'}</Table.Td><Table.Td>{m.subject||'—'}</Table.Td><Table.Td>{m.marks??'—'} / {m.max_marks??'—'}</Table.Td><Table.Td>{m.grade||'—'}</Table.Td></Table.Tr>)}</Table.Tbody></Table></>}</Stack></Card>)}
  {!data.staff&&!data.students.length&&<Card withBorder><Text c="dimmed">This account is not linked to a profile. Ask an administrator to recreate the link.</Text></Card>}</Stack></Container>;
}
