import Database from "./sqlite";

export const SCHEMA_VERSION = 4;

const TABLES = [
  "CREATE TABLE IF NOT EXISTS schools(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, academic_year TEXT, type TEXT);",
  "CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE, password_hash TEXT, role TEXT, name TEXT);",
  "CREATE TABLE IF NOT EXISTS user_staff_links(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, staff_id INTEGER NOT NULL UNIQUE);",
  "CREATE TABLE IF NOT EXISTS user_student_links(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, student_id INTEGER NOT NULL, relationship TEXT NOT NULL DEFAULT 'student', PRIMARY KEY(user_id,student_id));",
  "CREATE TABLE IF NOT EXISTS lms_spaces(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT, subject_id INTEGER, section_id INTEGER NOT NULL, created_by INTEGER NOT NULL, is_published INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), UNIQUE(subject_id,section_id));",
  "CREATE TABLE IF NOT EXISTS lms_modules(id INTEGER PRIMARY KEY AUTOINCREMENT, space_id INTEGER NOT NULL REFERENCES lms_spaces(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT, sort_order INTEGER DEFAULT 0, is_published INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS lms_lessons(id INTEGER PRIMARY KEY AUTOINCREMENT, module_id INTEGER NOT NULL REFERENCES lms_modules(id) ON DELETE CASCADE, title TEXT NOT NULL, content TEXT, objectives TEXT, resources TEXT, sort_order INTEGER DEFAULT 0, is_published INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS lms_assignments(id INTEGER PRIMARY KEY AUTOINCREMENT, space_id INTEGER NOT NULL REFERENCES lms_spaces(id) ON DELETE CASCADE, module_id INTEGER REFERENCES lms_modules(id) ON DELETE SET NULL, title TEXT NOT NULL, instructions TEXT, due_date TEXT, max_points REAL DEFAULT 100, is_published INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS lms_submissions(id INTEGER PRIMARY KEY AUTOINCREMENT, assignment_id INTEGER NOT NULL REFERENCES lms_assignments(id) ON DELETE CASCADE, student_id INTEGER NOT NULL, content TEXT, attachment TEXT, status TEXT DEFAULT 'submitted', submitted_at TEXT DEFAULT (datetime('now')), score REAL, feedback TEXT, graded_by INTEGER, graded_at TEXT, UNIQUE(assignment_id,student_id));",
  "CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY, value TEXT);",
  "CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT, first_name TEXT, middle_name TEXT, last_name TEXT, email TEXT, phone TEXT, gender TEXT, birthdate TEXT, alt_id TEXT, enrolled INTEGER DEFAULT 0);",
  "CREATE TABLE IF NOT EXISTS staff(id INTEGER PRIMARY KEY AUTOINCREMENT, first_name TEXT, last_name TEXT, email TEXT, phone TEXT, profile TEXT, title TEXT);",
  "CREATE TABLE IF NOT EXISTS courses(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);",
  "CREATE TABLE IF NOT EXISTS subjects(id INTEGER PRIMARY KEY AUTOINCREMENT, course_id INTEGER, name TEXT, code TEXT, type TEXT, weekly_periods INTEGER DEFAULT 0, is_lab INTEGER DEFAULT 0, mandatory INTEGER DEFAULT 1);",
  "CREATE TABLE IF NOT EXISTS gradelevels(id INTEGER PRIMARY KEY AUTOINCREMENT, short_name TEXT, title TEXT);",
  "CREATE TABLE IF NOT EXISTS classrooms(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, code TEXT, capacity INTEGER, room_type TEXT, is_active INTEGER DEFAULT 1);",
  "CREATE TABLE IF NOT EXISTS floorplans(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, data TEXT);",
  "CREATE TABLE IF NOT EXISTS classes(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, grade_level TEXT, course_id INTEGER);",
  "CREATE TABLE IF NOT EXISTS sections(id INTEGER PRIMARY KEY AUTOINCREMENT, class_id INTEGER, name TEXT, teacher_id INTEGER, capacity INTEGER, room_id INTEGER);",
  "CREATE TABLE IF NOT EXISTS teacher_subjects(id INTEGER PRIMARY KEY AUTOINCREMENT, staff_id INTEGER NOT NULL, subject_id INTEGER NOT NULL, priority INTEGER DEFAULT 1, UNIQUE(staff_id, subject_id));",
  "CREATE TABLE IF NOT EXISTS periods(id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL, period_type TEXT DEFAULT 'period', start_time TEXT NOT NULL, end_time TEXT NOT NULL, sort_order INTEGER DEFAULT 0);",
  "CREATE TABLE IF NOT EXISTS timetable_entries(id INTEGER PRIMARY KEY AUTOINCREMENT, section_id INTEGER NOT NULL, period_id INTEGER NOT NULL, day_of_week INTEGER NOT NULL, subject_id INTEGER, staff_id INTEGER, room_id INTEGER, UNIQUE(section_id, period_id, day_of_week));",
  "CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT);",
  "CREATE TABLE IF NOT EXISTS academic_years(id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL, start_date TEXT, end_date TEXT, is_active INTEGER DEFAULT 0, is_closed INTEGER DEFAULT 0);",
  "CREATE TABLE IF NOT EXISTS terms(id INTEGER PRIMARY KEY AUTOINCREMENT, year_id INTEGER NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE, label TEXT NOT NULL, start_date TEXT, end_date TEXT, is_active INTEGER DEFAULT 0);",
  "CREATE TABLE IF NOT EXISTS substitutions(id INTEGER PRIMARY KEY AUTOINCREMENT, original_entry_id INTEGER NOT NULL, original_staff_id INTEGER NOT NULL, substitute_staff_id INTEGER, date TEXT NOT NULL, reason TEXT, status TEXT DEFAULT 'pending', created_at TEXT DEFAULT (datetime('now')), resolved_at TEXT, UNIQUE(original_entry_id, date));",
  "CREATE TABLE IF NOT EXISTS departments(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, head_staff_id INTEGER);",
  "CREATE TABLE IF NOT EXISTS leave_requests(id INTEGER PRIMARY KEY AUTOINCREMENT, staff_id INTEGER NOT NULL, leave_type TEXT DEFAULT 'sick', from_date TEXT NOT NULL, to_date TEXT NOT NULL, reason TEXT, status TEXT DEFAULT 'pending', approved_by INTEGER, approved_at TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS exams(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, exam_type TEXT DEFAULT 'unit', academic_year_id INTEGER, term_id INTEGER, start_date TEXT, end_date TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS exam_schedules(id INTEGER PRIMARY KEY AUTOINCREMENT, exam_id INTEGER NOT NULL, subject_id INTEGER, section_id INTEGER, date TEXT, start_time TEXT, end_time TEXT, room_id INTEGER, invigilator_id INTEGER, UNIQUE(exam_id, subject_id, section_id));",
  "CREATE TABLE IF NOT EXISTS exam_marks(id INTEGER PRIMARY KEY AUTOINCREMENT, exam_id INTEGER NOT NULL, student_id INTEGER NOT NULL, subject_id INTEGER NOT NULL, marks_obtained REAL, max_marks REAL DEFAULT 100, grade TEXT, remarks TEXT, UNIQUE(exam_id, student_id, subject_id));",
  "CREATE TABLE IF NOT EXISTS salary_structures(id INTEGER PRIMARY KEY AUTOINCREMENT, staff_id INTEGER NOT NULL UNIQUE, basic REAL DEFAULT 0, hra REAL DEFAULT 0, da REAL DEFAULT 0, ta REAL DEFAULT 0, other_allowances REAL DEFAULT 0, pf_deduction REAL DEFAULT 0, pt_deduction REAL DEFAULT 0, other_deductions REAL DEFAULT 0, effective_from TEXT, updated_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS payslips(id INTEGER PRIMARY KEY AUTOINCREMENT, staff_id INTEGER NOT NULL, month TEXT NOT NULL, basic REAL, hra REAL, da REAL, ta REAL, other_allowances REAL, pf_deduction REAL, pt_deduction REAL, other_deductions REAL, gross REAL, net REAL, working_days INTEGER, paid_days INTEGER, generated_at TEXT DEFAULT (datetime('now')), UNIQUE(staff_id, month));",
  "CREATE TABLE IF NOT EXISTS module_settings(key TEXT PRIMARY KEY, display_name TEXT NOT NULL, enabled INTEGER DEFAULT 1, min_level INTEGER DEFAULT 5);",
  "CREATE TABLE IF NOT EXISTS import_jobs(id INTEGER PRIMARY KEY AUTOINCREMENT, source_type TEXT NOT NULL, source_path TEXT, status TEXT DEFAULT 'pending', rows_imported INTEGER DEFAULT 0, rows_failed INTEGER DEFAULT 0, error TEXT, started_at TEXT, completed_at TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, action TEXT NOT NULL, resource_type TEXT, resource_id INTEGER, detail TEXT, ip TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS roles(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, permissions TEXT DEFAULT '{}');",
  "CREATE TABLE IF NOT EXISTS backup_config(id INTEGER PRIMARY KEY, schedule TEXT DEFAULT 'daily', destinations TEXT DEFAULT '[]', last_backup_at TEXT, enabled INTEGER DEFAULT 1);",
  "CREATE TABLE IF NOT EXISTS backup_log(id INTEGER PRIMARY KEY AUTOINCREMENT, filename TEXT NOT NULL, path TEXT, size_bytes INTEGER, status TEXT DEFAULT 'ok', created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS activities(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, activity_type TEXT DEFAULT 'field_visit', date TEXT, end_date TEXT, venue TEXT, description TEXT, status TEXT DEFAULT 'planned', created_by INTEGER, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS faculty_plans(id INTEGER PRIMARY KEY AUTOINCREMENT, period_type TEXT NOT NULL CHECK(period_type IN ('daily','weekly','monthly')), title TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, section_id INTEGER, subject_id INTEGER, lessons TEXT, activities TEXT, schedule TEXT, objectives TEXT, resources TEXT, assessment TEXT, notes TEXT, status TEXT DEFAULT 'draft', created_by INTEGER NOT NULL, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS activity_staff(id INTEGER PRIMARY KEY AUTOINCREMENT, activity_id INTEGER NOT NULL, staff_id INTEGER NOT NULL, role TEXT DEFAULT 'in_charge', UNIQUE(activity_id, staff_id));",
  "CREATE TABLE IF NOT EXISTS activity_sections(id INTEGER PRIMARY KEY AUTOINCREMENT, activity_id INTEGER NOT NULL, section_id INTEGER NOT NULL, student_count INTEGER, UNIQUE(activity_id, section_id));",
  "CREATE TABLE IF NOT EXISTS activity_expenses(id INTEGER PRIMARY KEY AUTOINCREMENT, activity_id INTEGER NOT NULL, head TEXT NOT NULL, amount REAL NOT NULL, notes TEXT);",
  "CREATE TABLE IF NOT EXISTS announcements(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, body TEXT, audience TEXT DEFAULT 'internal', is_draft INTEGER DEFAULT 0, published_at TEXT, created_by INTEGER, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS meetings(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, meeting_type TEXT DEFAULT 'staff', date TEXT NOT NULL, start_time TEXT, end_time TEXT, venue TEXT, agenda TEXT, minutes TEXT, status TEXT DEFAULT 'scheduled', created_by INTEGER, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS meeting_attendees(id INTEGER PRIMARY KEY AUTOINCREMENT, meeting_id INTEGER NOT NULL, staff_id INTEGER, UNIQUE(meeting_id, staff_id));",
  "CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT, assigned_to INTEGER, department_id INTEGER, due_date TEXT, priority TEXT DEFAULT 'normal', status TEXT DEFAULT 'pending', created_by INTEGER, completed_at TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS reminders(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, tag TEXT DEFAULT 'normal', due_date TEXT, notes TEXT, done INTEGER DEFAULT 0, created_by INTEGER, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS transport_vehicles(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, driver_name TEXT, driver_phone TEXT, capacity INTEGER, notes TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS transport_routes(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, vehicle_id INTEGER, fare REAL, notes TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS transport_stops(id INTEGER PRIMARY KEY AUTOINCREMENT, route_id INTEGER NOT NULL, name TEXT NOT NULL, pickup_time TEXT, sort_order INTEGER DEFAULT 0);",
  "CREATE TABLE IF NOT EXISTS transport_assignments(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, route_id INTEGER NOT NULL, stop_id INTEGER, created_at TEXT DEFAULT (datetime('now')), UNIQUE(student_id));",
  "CREATE TABLE IF NOT EXISTS issued_items(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, item_type TEXT NOT NULL, issued INTEGER DEFAULT 0, issued_date TEXT, marked_by INTEGER, UNIQUE(student_id, item_type));",
  "CREATE TABLE IF NOT EXISTS visitors(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, phone TEXT, purpose TEXT, whom_to_meet TEXT, date TEXT NOT NULL, in_time TEXT, out_time TEXT, created_by INTEGER, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS library_books(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, author TEXT, isbn TEXT, category TEXT, total_copies INTEGER DEFAULT 1, available_copies INTEGER DEFAULT 1, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS library_loans(id INTEGER PRIMARY KEY AUTOINCREMENT, book_id INTEGER NOT NULL, student_id INTEGER NOT NULL, issued_date TEXT DEFAULT (date('now')), due_date TEXT, returned_date TEXT, created_by INTEGER, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS scholarships(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, name TEXT NOT NULL, kind TEXT DEFAULT 'amount', value REAL DEFAULT 0, notes TEXT, awarded_date TEXT DEFAULT (date('now')), created_by INTEGER, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS fee_heads(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT, is_optional INTEGER DEFAULT 0);",
  "CREATE TABLE IF NOT EXISTS fee_structures(id INTEGER PRIMARY KEY AUTOINCREMENT, academic_year_id INTEGER, class_id INTEGER, fee_head_id INTEGER NOT NULL, amount REAL NOT NULL, due_date TEXT, UNIQUE(academic_year_id, class_id, fee_head_id));",
  "CREATE TABLE IF NOT EXISTS fee_payments(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, fee_head_id INTEGER NOT NULL, academic_year_id INTEGER, amount_paid REAL NOT NULL, payment_date TEXT DEFAULT (date('now')), payment_mode TEXT DEFAULT 'cash', reference TEXT, receipt_no TEXT, collected_by INTEGER, notes TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS section_students(id INTEGER PRIMARY KEY AUTOINCREMENT, section_id INTEGER NOT NULL, student_id INTEGER NOT NULL, enrolled_date TEXT, UNIQUE(section_id, student_id));",
  "CREATE TABLE IF NOT EXISTS student_attendance(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, section_id INTEGER NOT NULL, date TEXT NOT NULL, period_id INTEGER NOT NULL, status TEXT DEFAULT 'present', marked_by INTEGER, note TEXT, marked_at TEXT DEFAULT (datetime('now')), UNIQUE(student_id, date, period_id));",
  "CREATE TABLE IF NOT EXISTS letters(id INTEGER PRIMARY KEY AUTOINCREMENT, ref_no TEXT, letter_date TEXT, recipient TEXT, subject TEXT, body TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS certificates(id INTEGER PRIMARY KEY AUTOINCREMENT, serial TEXT, cert_type TEXT, student_id INTEGER, student_name TEXT, title TEXT, body TEXT, issued_date TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS sports_events(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, sport TEXT, event_date TEXT, event_time TEXT, venue TEXT, notes TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS sports_results(id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER, participant TEXT, house TEXT, position INTEGER, points INTEGER DEFAULT 0, note TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS clubs(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, logo TEXT, lead_staff TEXT, meeting_day TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS club_members(id INTEGER PRIMARY KEY AUTOINCREMENT, club_id INTEGER, student_id INTEGER, student_name TEXT, role TEXT, joined_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS student_documents(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, doc_type TEXT, file_name TEXT, mime TEXT, data TEXT, verified INTEGER DEFAULT 0, uploaded_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS student_marks(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, term TEXT, subject TEXT, max_marks REAL, marks REAL, grade TEXT, remarks TEXT, recorded_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS board_registrations(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, exam_year TEXT, registration_no TEXT, loc_status TEXT, admit_card_status TEXT, board_subjects TEXT, notes TEXT, updated_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS student_communications(id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, channel TEXT, direction TEXT, subject TEXT, body TEXT, acknowledged INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS compliance_certificates(id INTEGER PRIMARY KEY AUTOINCREMENT, scope TEXT, staff_id INTEGER, cert_type TEXT, authority TEXT, reference_no TEXT, issue_date TEXT, expiry_date TEXT, document TEXT, notes TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS exam_archives(id INTEGER PRIMARY KEY AUTOINCREMENT, academic_year TEXT, exam_name TEXT, material_type TEXT, subject TEXT, class_name TEXT, document TEXT, retention_until TEXT, disposed INTEGER DEFAULT 0, disposed_at TEXT, notes TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS practical_exams(id INTEGER PRIMARY KEY AUTOINCREMENT, subject TEXT, class_name TEXT, exam_date TEXT, batch TEXT, internal_examiner TEXT, external_examiner TEXT, lab TEXT, max_marks REAL, evidence TEXT, geo TEXT, marks_locked INTEGER DEFAULT 0, locked_at TEXT, notes TEXT, created_at TEXT DEFAULT (datetime('now')));",
  "CREATE TABLE IF NOT EXISTS practical_marks(id INTEGER PRIMARY KEY AUTOINCREMENT, practical_exam_id INTEGER NOT NULL, student_name TEXT, marks REAL, created_at TEXT DEFAULT (datetime('now')));",
] as const;

const COLUMN_MIGRATIONS = [
  "ALTER TABLE schools ADD COLUMN type TEXT",
  "ALTER TABLE schools ADD COLUMN address TEXT",
  "ALTER TABLE schools ADD COLUMN principal_name TEXT",
  "ALTER TABLE schools ADD COLUMN logo TEXT",
  "ALTER TABLE schools ADD COLUMN signature TEXT",
  "ALTER TABLE schools ADD COLUMN cert_bg TEXT",
  "ALTER TABLE schools ADD COLUMN affiliation_no TEXT",
  "ALTER TABLE schools ADD COLUMN school_code TEXT",
  "ALTER TABLE schools ADD COLUMN udise_code TEXT",
  "ALTER TABLE sports_events ADD COLUMN home_club_id INTEGER",
  "ALTER TABLE sports_events ADD COLUMN away_club_id INTEGER",
  "ALTER TABLE sports_results ADD COLUMN club_id INTEGER",
  "ALTER TABLE students ADD COLUMN guardian_name TEXT",
  "ALTER TABLE students ADD COLUMN guardian_phone TEXT",
  "ALTER TABLE students ADD COLUMN guardian_relation TEXT",
  "ALTER TABLE students ADD COLUMN address TEXT",
  "ALTER TABLE staff ADD COLUMN department TEXT",
  "ALTER TABLE staff ADD COLUMN join_date TEXT",
  "ALTER TABLE staff ADD COLUMN employee_id TEXT",
  "ALTER TABLE staff ADD COLUMN department_id INTEGER",
  "ALTER TABLE students ADD COLUMN card_uid TEXT",
  "ALTER TABLE students ADD COLUMN father_name TEXT",
  "ALTER TABLE students ADD COLUMN mother_name TEXT",
  "ALTER TABLE students ADD COLUMN blood_group TEXT",
  "ALTER TABLE students ADD COLUMN admission_date TEXT",
  "ALTER TABLE students ADD COLUMN nationality TEXT",
  "ALTER TABLE students ADD COLUMN category TEXT",
  "ALTER TABLE students ADD COLUMN emergency_contact TEXT",
  "ALTER TABLE students ADD COLUMN medical_notes TEXT",
  "ALTER TABLE students ADD COLUMN status TEXT DEFAULT 'Active'",
  "ALTER TABLE students ADD COLUMN cwsn TEXT",
  "ALTER TABLE students ADD COLUMN lock_state TEXT DEFAULT 'Draft'",
  "ALTER TABLE users ADD COLUMN role_id INTEGER",
  "ALTER TABLE users ADD COLUMN level INTEGER DEFAULT 3",
  "ALTER TABLE students ADD COLUMN apaar_id TEXT",
  "ALTER TABLE students ADD COLUMN pen TEXT",
  "ALTER TABLE students ADD COLUMN aadhaar TEXT",
  "ALTER TABLE students ADD COLUMN religion TEXT",
  "ALTER TABLE students ADD COLUMN mother_tongue TEXT",
  "ALTER TABLE students ADD COLUMN permanent_address TEXT",
  "ALTER TABLE students ADD COLUMN photo TEXT",
  "ALTER TABLE students ADD COLUMN father_occupation TEXT",
  "ALTER TABLE students ADD COLUMN father_employer TEXT",
  "ALTER TABLE students ADD COLUMN father_income TEXT",
  "ALTER TABLE students ADD COLUMN father_phone TEXT",
  "ALTER TABLE students ADD COLUMN father_email TEXT",
  "ALTER TABLE students ADD COLUMN father_aadhaar TEXT",
  "ALTER TABLE students ADD COLUMN mother_occupation TEXT",
  "ALTER TABLE students ADD COLUMN mother_employer TEXT",
  "ALTER TABLE students ADD COLUMN mother_income TEXT",
  "ALTER TABLE students ADD COLUMN mother_phone TEXT",
  "ALTER TABLE students ADD COLUMN mother_email TEXT",
  "ALTER TABLE students ADD COLUMN mother_aadhaar TEXT",
  "ALTER TABLE students ADD COLUMN guardian_email TEXT",
  "ALTER TABLE students ADD COLUMN guardian_aadhaar TEXT",
  "ALTER TABLE students ADD COLUMN admission_class TEXT",
  "ALTER TABLE students ADD COLUMN previous_school TEXT",
  "ALTER TABLE students ADD COLUMN previous_board TEXT",
  "ALTER TABLE students ADD COLUMN tc_number TEXT",
  "ALTER TABLE students ADD COLUMN migration_number TEXT",
  "ALTER TABLE students ADD COLUMN verification_status TEXT",
] as const;

export function migrateSchema(database: Database.Database): void {
  database.pragma("foreign_keys = ON");
  const migrate = database.transaction(() => {
    for (const statement of TABLES) database.exec(statement);
    for (const statement of COLUMN_MIGRATIONS) {
      try {
        database.exec(statement);
      } catch (error) {
        if (
          !(error instanceof Error) ||
          !error.message.includes("duplicate column name")
        )
          throw error;
      }
    }
    database.pragma(`user_version = ${SCHEMA_VERSION}`);
  });
  migrate();
}
